addons/console_server:
    PORT: 23515

cooperative/cpf_wifi_server:
    broadcast_port: 24515

cooperative/cpf_wifi_client:
    broadcast_port: 24515


controls/inner_loops_pid:
        topics:
                subscribers:
                        state:
                                "/#vehicle#/nav/filter/state"
