node_frequency: 10

sonar_range: 15
sonar_pos_body: [0.22, 0, -0.19]

# Cylinder : 5.625 m
# Sphere 15 posts:
# net_radius: 6.55
# dist_between_posts: 2.66

# Sphere 20 posts:
net_radius: 6.4
dist_between_posts: 2.025
net_sphere_radius: []
number_posts: 20

dist_critical: 3.0

distance_of_outliers: 30
nmin_points: 50


desired_distance: 2.5
sway_desired: 0.2
current_velocity: [0, 0]
k1: 1.0
k2: 0.00444
#k2: 0.0025

#kp_dist: 0.03 # For low speeds
#kp_dist: 0.3
kp_dist: 0.08
ki_dist: 0.0

pos_center: [30, 0]
utm_pos_inertial: [4290794.43, 491936.56]

inspection_flag: True

Vehicle: /bluerov_heavy0
