node_frequency: 10

# Cylinder : 5.625 m
# Sphere : 6.325 m
#net_radius: 6.325
net_radius: 6.325
sonar_range: 15
dist_between_posts: 2.60

dist_critical: 3

distance_of_outliers: 30
nmin_points: 500


desired_distance: 2.5
sway_desired: 0.2
k1: 2.0
k2: 0.00444

kp_dist: 0.05
ki_dist: 0.0

pos_center: [30, 0]
utm_pos_inertial: [4290794.43, 491936.56]

inspection_flag: True

Vehicle: /bluerov_heavy0